[package]
name = "logix"
version = "0.2.0"
description = "An experimental command-line tool for simplified and enhanced configuration management across multiple systems."
repository = "https://github.com/logix-tool/logix"
edition = "2021"
authors = [
  "Bjørn Ove Hay Andersen <bjrnove@gmail.com>",
  "Gigantos <gigantos@gigantos.net>",
]
readme = "README.md"
license = "MPL-2.0"
categories = ["command-line-utilities", "config"]

[badges]
maintainance = { status = "experimental" }

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
directories = "5.0.1"
logix-type = "0.4.1"
logix-vfs = "0.6.0"
tempfile = "3.8.1"
thiserror = "1.0.50"
