[package]
name = "logix"
version = "0.2.0"
description = "An experimental command-line tool for simplified and enhanced configuration management across multiple systems."
repository = "https://github.com/logix-tool/logix"
edition = "2021"
authors = [
  "Bjørn Ove Hay Andersen <bjrnove@gmail.com>",
  "Gigantos <gigantos@gigantos.net>",
]
readme = "README.md"
license = "MPL-2.0"
categories = ["command-line-utilities", "config"]

[badges]
maintainance = { status = "experimental" }

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
directories = "5.0.1"
logix-type = "0.5.0"
logix-vfs = "0.7.0"
tempfile = "3.10.0"
thiserror = "1.0.56"
walkdir = "2.4.0"

[workspace]
members = [
  "xtask",
]
