[package]
name = "logix"
version = "0.1.0"
edition = "2021"
authors = [
  "Bjørn Ove Hay Andersen <bjrnove@gmail.com>"
]
readme = "README.md"
license = "MPL-2.0"
license-file = "LICENSE"
categories = ["command-line-utilities", "config"]

[badges]
maintainance = { status = "experimental" }

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
