[package]
name = "logix"
version.workspace = true
description = "An experimental command-line tool for simplified and enhanced configuration management across multiple systems."
repository = "https://github.com/logix-tool/logix"
edition.workspace = true
authors.workspace = true
readme = "README.md"
license.workspace = true
categories = ["command-line-utilities", "config"]

[badges]
maintainance = { status = "experimental" }

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
dirs = "5.0.1"
logix-type = "0.11.0"
logix-vfs = "0.9.0"
tempfile = "3.10.1"
thiserror = "1.0.61"
walkdir = "2.5.0"

[workspace]
members = [
  "xtask",
]

[workspace.package]
version = "0.3.1"
authors = [
  "Gigantos <gigantos@gigantos.net>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
